"""add_user_preference

Revision ID: 04cbfe3b3dd1
Revises: fb99167eb709
Create Date: 2026-06-27 05:53:13.712477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04cbfe3b3dd1'
down_revision: Union[str, None] = 'fb99167eb709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preference', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preference')
    # ### end Alembic commands ###
